# Generated by Django 5.0.3 on 2024-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0002_authentication_menu_delete_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
