# Generated by Django 5.0.3 on 2024-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0008_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
