# Generated by Django 5.0.3 on 2024-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0009_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
