# Generated by Django 5.0.3 on 2024-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0005_alter_authentication_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
